version: '3.3'
services:
  mydb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'willy'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  manager:
    image: jandur/oompa-manager:0.0.1-SNAPSHOT
    container_name: oompa_manager
    ports:
      - '8080:8080'
    depends_on:
      - mydb
    networks:
      - net
    healthcheck:
      test: if [[ $${APP_STATUS} -eq 200 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mysql-db:
networks:
  net:
    driver: bridge
